# Generated by Django 3.2.8 on 2021-10-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='main.IngredientInRecipe', to='main.Ingredient'),
        ),
    ]
