# Generated by Django 3.2.8 on 2021-10-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ingredientinrecipe_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.unit'),
        ),
    ]
