# Generated by Django 3.2.8 on 2021-10-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ingredientinrecipe_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
