# Generated by Django 3.2.8 on 2021-10-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211023_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
