# Generated by Django 3.2.8 on 2021-11-09 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_instruction_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/images/'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
