# Generated by Django 3.2.8 on 2022-01-12 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_rename_description_instruction_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='ingredient_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='ingredient_in_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
