# Generated by Django 3.2.8 on 2022-01-13 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ingredientinrecipe_ingredient_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='main.recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='ingredient_list',
        ),
        migrations.CreateModel(
            name='ShoppingListElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ingredient')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shoppinglist')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.unit')),
            ],
        ),
    ]
