# Generated by Django 3.2.8 on 2022-01-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_shoppinglistelement_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='recipe/images/'),
        ),
    ]
